steps:
  # Build the container image
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/fusion-scanner:$COMMIT_SHA", "."]

  # Push the container image to Container Registry
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/fusion-scanner:$COMMIT_SHA"]

  # Deploy container image to Cloud Run
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      - "run"
      - "deploy"
      - "fusion-scanner"
      - "--image"
      - "gcr.io/$PROJECT_ID/fusion-scanner:$COMMIT_SHA"
      - "--region"
      - "us-central1"
      - "--platform"
      - "managed"
      - "--port"
      - "8080"
      - "--allow-unauthenticated"
      - "--memory"
      - "2Gi"
      - "--cpu"
      - "2"
      - "--max-instances"
      - "10"
      - "--set-env-vars"
      - "NODE_ENV=production"

images:
  - "gcr.io/$PROJECT_ID/fusion-scanner:$COMMIT_SHA"

timeout: "1200s"
