apiVersion: v1
kind: Secret
metadata:
  name: vulnerability-scanner-secrets
  namespace: vulnerability-scanner
  labels:
    app: vulnerability-scanner
    component: secrets
type: Opaque
data:
  # Base64 encoded secrets - CHANGE THESE IN PRODUCTION!
  # session-secret: echo -n "your-secure-session-secret-change-in-production" | base64
  # jwt-secret: echo -n "your-secure-jwt-secret-change-in-production" | base64
  session-secret: eW91ci1zZWN1cmUtc2Vzc2lvbi1zZWNyZXQtY2hhbmdlLWluLXByb2R1Y3Rpb24=
  jwt-secret: eW91ci1zZWN1cmUtand0LXNlY3JldC1jaGFuZ2UtaW4tcHJvZHVjdGlvbg==
---
apiVersion: v1
kind: Secret
metadata:
  name: registry-secret
  namespace: vulnerability-scanner
  labels:
    app: vulnerability-scanner
    component: registry
type: kubernetes.io/dockerconfigjson
data:
  # Docker registry credentials if needed
  # kubectl create secret docker-registry registry-secret --docker-server=<server> --docker-username=<username> --docker-password=<password> --docker-email=<email> --dry-run=client -o yaml
  .dockerconfigjson: eyJhdXRocyI6e319
