apiVersion: v2
name: vulnerability-scanner
description: AI-Powered Vulnerability Assessment Platform
type: application
version: 1.0.0
appVersion: "1.0.0"
keywords:
  - security
  - vulnerability
  - scanner
  - ai
  - assessment
home: https://github.com/your-org/vulnerability-scanner
sources:
  - https://github.com/your-org/vulnerability-scanner
maintainers:
  - name: Security Team
    email: security@your-org.com
icon: https://your-org.com/icons/vulnerability-scanner.png
annotations:
  category: Security
  licenses: MIT
dependencies:
  - name: redis
    version: 17.11.3
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
  - name: postgresql
    version: 12.5.8
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
