apiVersion: apps/v1
kind: Deployment
metadata:
  name: vulnerability-scanner
spec:
  replicas: 5
  template:
    spec:
      containers:
        - name: vulnerability-scanner
          resources:
            requests:
              cpu: 1000m
              memory: 2Gi
            limits:
              cpu: 4000m
              memory: 8Gi
          env:
            - name: NODE_ENV
              value: production
            - name: LOG_LEVEL
              value: info
            - name: MAX_CONCURRENT_SCANS
              value: "10"
            - name: NUCLEI_RATE_LIMIT
              value: "300"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vulnerability-scanner-redis
spec:
  template:
    spec:
      containers:
        - name: redis
          resources:
            requests:
              cpu: 200m
              memory: 512Mi
            limits:
              cpu: 1000m
              memory: 1Gi
