apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: vulnerability-scanner

resources:
  - ../../k8s/00-namespace.yaml
  - ../../k8s/01-configmap.yaml
  - ../../k8s/02-secrets.yaml
  - ../../k8s/03-storage.yaml
  - ../../k8s/04-redis.yaml
  - ../../k8s/05-scanner-deployment.yaml
  - ../../k8s/06-scanner-service.yaml
  - ../../k8s/07-nginx-ingress.yaml
  - ../../k8s/08-autoscaling.yaml
  - ../../k8s/09-monitoring.yaml
  - ../../k8s/10-backup.yaml

commonLabels:
  app.kubernetes.io/name: vulnerability-scanner
  app.kubernetes.io/version: v1.0.0
  app.kubernetes.io/component: security-platform

images:
  - name: vulnerability-scanner
    newTag: latest

configMapGenerator:
  - name: app-info
    literals:
      - version=1.0.0
      - build=latest
      - component=vulnerability-scanner

secretGenerator:
  - name: app-secrets
    literals:
      - api-key=placeholder
      - webhook-secret=placeholder

replicas:
  - name: vulnerability-scanner
    count: 2
